version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./scripts/initdb.d/:/docker-entrypoint-initdb.d/:ro
  dm:
    build:
      context: .
      dockerfile: docker/dm.Dockerfile
    expose:
      - 5000
    restart: always
  wallet:
    build:
      context: .
      dockerfile: docker/wallet.Dockerfile
    expose:
      - 5000
    restart: always
  shop:
    build:
      context: .
      dockerfile: docker/shop.Dockerfile
    expose:
      - 5000
    restart: always
  shop_gateway:
    build:
      context: .
      dockerfile: docker/shop_gateway.Dockerfile
    command:
      - /gateway
      - -grpc-server-endpoint
      - shop:5000
    ports:
      - 8080:8080
    restart: always
  wallet_gateway:
    build:
      context: .
      dockerfile: docker/wallet_gateway.Dockerfile
    command:
      - /gateway
      - -grpc-server-endpoint
      - wallet:5000
    ports:
      - 8081:8080
