version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./scripts/initdb.d/:/docker-entrypoint-initdb.d/:ro
  reverseproxy:
    image: nginx:mainline
    ports:
      - 8080:80
    restart: always
    depends_on:
      - bank1
      - bank2
      - app
    volumes:
      - ./scripts/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  dm:
    build:
      context: .
      dockerfile: docker/dm.Dockerfile
    expose:
      - 5000
    restart: always
    depends_on:
      - mysql
  bank1:
    build:
      context: .
      dockerfile: docker/bank.Dockerfile
    command: [ "/bank", "-bank-id", "1" ]
    expose:
      - 5000
    restart: always
    depends_on:
      - dm
      - mysql
  bank2:
    build:
      context: .
      dockerfile: docker/bank.Dockerfile
    command: [ "/bank", "-bank-id", "2" ]
    expose:
      - 5000
    restart: always
    depends_on:
      - dm
      - mysql
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    expose:
      - 5000
    restart: always
    depends_on:
      - dm
      - bank1
      - bank2
      - mysql
