CREATE DATABASE dm;
USE dm;
CREATE TABLE global_tx (
    gid VARCHAR(64) PRIMARY KEY NOT NULL,
    expire_at TIMESTAMP NOT NULL
);
CREATE TABLE local_tx (
    branch_id VARCHAR(64) PRIMARY KEY NOT NULL,
    gid VARCHAR(64) NOT NULL,
    callback_url VARCHAR(512) NOT NULL,
    FOREIGN KEY (gid) REFERENCES global_tx(gid)
);

CREATE DATABASE bank1;
USE bank1;
CREATE TABLE wallet (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    balance DECIMAL NOT NULL
);
INSERT INTO wallet(id,balance) VALUES(1,100);

CREATE DATABASE bank2;
USE bank2;
CREATE TABLE wallet (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    balance DECIMAL NOT NULL
);
INSERT INTO wallet(id,balance) VALUES(2,100);
